config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'
  devise_for :users
  root 'stories#index'
  resources :stories do
    collection do
      get 'rank'
    end
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
  resources :categories, only: [:new, :create, :show]
  resources :subjects, only: [:new, :create]
  resources :purposes, only: [:new, :create]
  resources :tales, only: [:new, :create]
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :story, optional: true
  mount_uploader :image, ImageUploader

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :story

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :story
  validates_uniqueness_of :story_id, scope: :user_id
end

app/models/purpose.rb
class Purpose < ApplicationRecord
  belongs_to :story, optional: true
  
  validates :content, presence: true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_one :category
  has_one :subject
  has_one :purpose
  has_one :tale
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  with_options presence: true do
    validates :category_id 
    validates :subject_id
    validates :purpose_id
    validates :tale_id
    validates :text
  end

end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :story, optional: true

  validates :content, presence: true
end

app/models/tale.rb
class Tale < ApplicationRecord
  belongs_to :story, optional: true
  
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        
  has_many :stories
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  with_options presence: true do
    validates :nickname
    validates :email
    validates :password
  end

  def already_liked?(story)
    self.likes.exists?(story_id: story.id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(story_id: params[:story_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(story_id: params[:story_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end



end

app/controllers/tales_controller.rb
class TalesController < ApplicationController
  def new
  end

  def create
    Tale.create(content: params[:content])
    redirect_to new_tale_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/purposes_helper.rb
module PurposesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tales_helper.rb
module TalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppStory28753</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <script src="https://kit.fontawesome.com/2f7db83b97.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
  
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、物語を作るアプリ
  </p>
  <h2 class='ad-footer-title'>
    気軽に楽しんで
  </h2>
  <%# <div class='store-btn'>
    <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%# <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  <%# </div> %> 
</div>
<%# //下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>HANYAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>HANYAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>AppSTORYについて</h2>
      <ul>
        <li><%= link_to 'AppSTORY ガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'AppSTORY ロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("appstory.png", class:"logo-white"), "#" %>
  <p>© HANYA</p>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("appstory-color.png", class:"app-story-icon"), "/" %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li class="category-book-list list-color" id="lists">カテゴリー</li>
      <li><%= link_to '人気', rank_stories_path, class: "brand-list" %></li>
    </ul>
    <ul class="category-lists hidden" id="pull-down">
        <li class="pull-down-list">
          <%= link_to "いい話","/categories/1",id:"pull-down-color" %>
        </li>
        <li class="pull-down-list">
          <%= link_to "恋の話","/categories/2",id:"pull-down-color" %>
        </li>
        <li class="pull-down-list">
          <%= link_to "泣ける話","/categories/3",id:"pull-down-color" %>
        </li>
        <li class="pull-down-list">
          <%= link_to "不思議な話","/categories/4",id:"pull-down-color" %>
        </li>
        <li class="pull-down-list">
          <%= link_to "怖い話","/categories/5",id:"pull-down-color" %>
        </li>
        <li class="pull-down-list">
          <%= link_to "笑い話","/categories/6",id:"pull-down-color" %>
        </li>
        <li class="pull-down-list">
          <%= link_to "スッキリ話","/categories/7",id:"pull-down-color" %>
        </li>
      </ul>
    <ul class='lists-right'>
      
      <% if user_signed_in? %>
        <li class="list-color"><%= link_to current_user.nickname, "/users/#{current_user.id}", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>

    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <%= image_tag "appstory-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("appstory-color.png", class:"second-logo"), "/" %>
</header>