config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'
  devise_for :users
  root 'stories#index'
  resources :stories do
    collection do
      get 'rank'
    end
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
  resources :categories, only: [:new, :create, :show]
  resources :subjects, only: [:new, :create]
  resources :purposes, only: [:new, :create]
  resources :tales, only: [:new, :create]
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :story, optional: true
  mount_uploader :image, ImageUploader

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :story

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :story
  validates_uniqueness_of :story_id, scope: :user_id
end

app/models/purpose.rb
class Purpose < ApplicationRecord
  belongs_to :story, optional: true
  
  validates :content, presence: true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_one :category
  has_one :subject
  has_one :purpose
  has_one :tale
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  with_options presence: true do
    validates :category_id 
    validates :subject_id
    validates :purpose_id
    validates :tale_id
    validates :text
  end

end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :story, optional: true

  validates :content, presence: true
end

app/models/tale.rb
class Tale < ApplicationRecord
  belongs_to :story, optional: true
  
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        
  has_many :stories
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  with_options presence: true do
    validates :nickname
    validates :email
    validates :password
  end

  def already_liked?(story)
    self.likes.exists?(story_id: story.id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      ActionCable.server.broadcast 'comment_channel', content: @comment, user: current_user
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, story_id: params[:story_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(story_id: params[:story_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(story_id: params[:story_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end



end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_params, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show]

  def index
    @stories = Story.includes(:user).order('created_at DESC').limit(10)
    @category = Category.select(:id,:image)
    @subject = Subject.all
    @purpose = Purpose.all
    @tale = Tale.all
    @ranks = Story.find(Like.group(:story_id).order("count(story_id) desc").limit(10).pluck(:story_id))
  end

  def new
    @story = Story.new
    @category = Category.all
    @subject = Subject.offset( rand(Subject.count) ).first
    @purpose = Purpose.offset( rand(Purpose.count) ).first
    @tale = Tale.offset( rand(Tale.count) ).first
    gon.subject = @subject
    gon.purpose = @purpose
    gon.tale = @tale
  end
  
  def create
    @story = Story.new(params_story)
    @story.user_id = current_user.id
    if @story.valid?
      @story.save
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    story = Story.find(params[:id])
    if story.valid?
      story.update(story_params)
      redirect_to story_path, method: :get
    else
      render 'edit'
    end
  end

  def destroy
    story = Story.find(params[:id])
    if story.valid? 
      story.destroy
      redirect_to root_path, method: :get
    else
      render 'show'
    end
  end

  def show
    @comment = Comment.new()
    @comments = @story.comments.includes(:user)
    @like = Like.new
  end

  def rank
    @ranks = Story.find(Like.group(:story_id).order('count(story_id) desc').limit(30).pluck(:story_id))
    @category = Category.select(:id,:image)
    @subject = Subject.all
    @purpose = Purpose.all
    @tale = Tale.all
  end

  private

  def set_params
    @story = Story.find(params[:id])
  end

  def params_story
    params.permit(:text, :category_id, :subject_id, :purpose_id, :tale_id)
  end

  def story_params
    params.require(:story).permit(:text, :category_id, :subject_id, :purpose_id, :tale_id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/controllers/tales_controller.rb
class TalesController < ApplicationController
  def new
  end

  def create
    Tale.create(content: params[:content])
    redirect_to new_tale_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ActionController::Live

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @stories = user.stories.order("created_at DESC")
    @subject = Subject.all
    @purpose = Purpose.all
    @tale = Tale.all
    @categories = Category.select(:id)
    @story = @stories.each do |story|
    gon.category = @categories[(story.category_id)-1].id
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/purposes_helper.rb
module PurposesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/tales_helper.rb
module TalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/stories/edit.html.erb
<%= render "shared/header" %>

<div class="edit-story">
  <div class="edit-main">
    <%= form_with(model: @story, local: true) do |form| %>
      <div class="edit-story-top">
        <h3>編集する</h3>
      </div>
      <div class="edit-story-box">
          <%= form.text_area :text, cols:"48", rows:"600", maxlength:"28800",class:"story-text edit-text" %>
      </div>
      <div class="edit-btn">
        <%= form.submit "投稿する", class:"edit-btn-submit" %>
      </div>
    <% end %>
  </div>
  <footer class="story_footer">
    <%= link_to image_tag("appstory.png", size:'280x80'), "/"   %>
  </footer>
</div>

app/views/stories/index.html.erb
<%= render "shared/header" %>
<div class="main">

  <%# 画面上部の「多くの物語に出会えるアプリ」帯部分 %>
  <div class="title-contents">
    <h2 class="service-title">
      多くの物語に出会えるアプリ
    </h2>
    <p class="service-explain">
      AppSTORYはだれでもかんたんに作る・読む事ができる
    </p>
    <p class="service-explain">
      アプリです
    </p>
    <%# <div class="store-btn">
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%# <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    <%# </div> %>
  </div>

  <%# AppSTORYが選ばれる3つの理由部分 %>
  <div class="select-reason-contents">
    <h2 class="title">
      AppSTORYが選ばれる3つの理由
    </h2>
    <ul class="reason-lists">
      <li class="list">
        <%= image_tag "appstory-icon-1.png", class:"list-pict" %>
        <span class="reason-list-number">1</span>
        <h3 class="reason-list-text">
          <span class="reason-list-blue-text">ちょっとの時間</span>
          で<br>すぐ読める
        </h3>
        <p class="reason-list-description">
          待ち時間や、気分転換に<br>使えます！
        </p>
      </li>
      <li class="list">
        <%= image_tag "appstory-icon-2.png", class:"list-pict" %>
        <span class="reason-list-number">2</span>
        <h3 class="reason-list-text">
          <span class="reason-list-blue-text">気軽に</span>
          物語が<br>作れちゃう！
        </h3>
        <p class="reason-list-description">
          出されたお題を使って<br>執筆へ
        </p>
      </li>
      <li class="list">
        <%= image_tag "appstory-icon-3.png", class:"list-pict" %>
        <span class="reason-list-number">3</span>
        <h3 class="reason-list-text">
          <span class="reason-list-blue-text">イイね</span>
          を貰って<br>嬉しい気分に！
        </h3>
        <p class="reason-list-description">
          気に入った作品などは<br>
          <span class="reason-list-blue-text">シェア</span>
          して多くの人に読んでもらえたら最高だね
        </p>
      </li>
    </ul>
  </div>
  <%# //AppSTORYが選ばれる3つの理由部分 %>


  <%# 人気作品一覧 %>
  <div class="story-contents">
    <h2 class="title">ピックアップカテゴリー</h2>
    <%= link_to "新規投稿作品", "stories/new", class: "subtitle" %>
    <ul class="book-lists">
      <% @stories.each do |story| %>
        <li class="books">
          <%= link_to story_path(story.id), method: :get do %>
            <div class="book-img-content">
              <%= image_tag @category[(story.category_id)-1].image.url, class: "book-img" %>
            </div>
            <div class="story-info">
              <h3 class="story-name">
                <span>
                  <%= @subject[(story.subject_id)-1].content %><br>
                  <%= @purpose[(story.purpose_id)-1].content %><br>
                  <%= @tale[(story.tale_id)-1].content %>
                </span>
              </h3>
              <div class="story-nickname">
                <p>
                  <%= story.user.nickname %>
                </p>
              </div>
              <div class="star-btn">
                <%= image_tag "star.png", class:"star-icon" %>
                <span class="star-count">
                  <%= story.liked_users.count  %>
                </span>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
      
      <% if @stories.blank? %>
        <li class="sample-books">
          <%= link_to '#' do %>
            <%= image_tag "appstory-icon4", class: "sample-img" %>
            <div class="sample-book-info">
              <h3 class="sample-book-name">
                作品を出版してね！
              </h3>
              <div class="sample-star-btn">
                <%= image_tag "star.png", class:"star-icon" %>
                <span class="star-count">0</span>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <%# //人気作品一覧 %>
  <div class="book-ranking">
    <%= link_to '人気ランキング', "stories/new", class: "rankings" %>
    <ul class="rank-book-lists">
      <% @ranks.each.with_index(1) do |story, i| %>
        <li class="rank-books">
          <div class="book-rank-name">
            <h2>第<span><%= i %></span>位</h2>
          </div>
          <%= link_to story_path(story.id), method: :get do %>
            <div class="book-img-content">
              <%= image_tag @category[(story.category_id)-1].image.url, class: "book-img" %>
            </div>
            <div class="story-info">
              <h3 class="story-name">
                <span>
                  <%= @subject[(story.subject_id)-1].content %><br>
                  <%= @purpose[(story.purpose_id)-1].content %><br>
                  <%= @tale[(story.tale_id)-1].content %>
                </span>
              </h3>
              <div class="story-rank-nickname">
                <p>
                  <%= story.user.nickname %>
                </p>
              </div>
              <div class="rank-star-btn">
                <%= image_tag "star.png", class:"star-icon" %>
                <span class="star-count">
                  <%= story.liked_users.count  %>
                </span>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<% if user_signed_in? %>
<div class="purchase-btn">
  <a href="stories/new">
    <%= image_tag "book-color3.png" , size: '550x80' ,class: "purchase-btn-icon" %>
  </a>
</div>
<% end %>
<%= render "shared/footer" %>

app/views/stories/new.html.erb
<div class="make＿story">

  <header class="appstory-logo">
  <%= link_to image_tag("appstory-color.png", size:'470x125'), "/" %>

  </header>
  <%= form_with model: @story, local: true do |s| %>
    <%= render 'shared/error_messages', model: s.object %>

    <%# カテゴリー選択 %>
    <div class="category">
      <h2><span>カテゴリー</span>を選んで下さい</h2>
      <div class="select_category">
        <div class="lists">
          <div class="icon">
            <input type="radio" class="list_icon" id="list_icon_01" name="category_id" value="1">
            <label for="list_icon_01" class="list_label"> 
                <%= image_tag @category[0].image.url, class:"icon_list" %><br>
                いい話 
            </label> 
          </div>
          <div class="icon">
            <input type="radio" class="list_icon" id="list_icon_02" name="category_id" value="2">
            <label for="list_icon_02" class="list_label">
              <%= image_tag @category[1].image.url, class:"icon_list"  %><br>
              恋の話
            </label>
          </div>
          <div class="icon">
            <input type="radio" class="list_icon" id="list_icon_03" name="category_id" value="3" >
            <label for="list_icon_03" class="list_label">
              <%= image_tag @category[2].image.url, class:"icon_list" %><br>
              泣ける話
            </label>
          </div>
          <div class="icon">
            <input type="radio" class="list_icon" id="list_icon_04" name="category_id" value="4">
            <label for="list_icon_04" class="list_label">
              <%= image_tag @category[3].image.url, class:"icon_list" %><br>
              不思議な話
            </label> 
          </div>
          <div class="icon">
            <input type="radio" class="list_icon" id="list_icon_05" name="category_id" value="5">
            <label for="list_icon_05" class="list_label">
              <%= image_tag @category[4].image.url, class:"icon_list" %><br>
              怖い話
            </label>
          </div>
          <div class="icon">
            <input type="radio" class="list_icon" id="list_icon_06" name="category_id" value="6">
            <label for="list_icon_06" class="list_label">
              <%= image_tag @category[5].image.url, class:"icon_list" %><br>
              笑い話
            </label> 
          </div>
          <div class="icon">
            <input type="radio" class="list_icon" id="list_icon_07" name="category_id" value="7">
            <label for="list_icon_07" class="list_label">
              <%= image_tag @category[6].image.url, class:"icon_list" %><br>
            スッキリ話
            </label>
          </div>
        </div>  
      </div>
    </div>
      <%# /カテゴリー選択 %>
      <%# お題作成 %>
    <div class="story_theme">
      <button type="button" id="start_button" >
        お題を作る
      </button>
      <div class="story_animation">
        <div class="story_anime">
          <h1 class="story_anime_theme">
            <span class="messages messages-0">
            </span>
            <span class="messages messages-1" >
              <%= @subject.content %>
            </span>
            <span class="messages messages-2">
              <%= @purpose.content %>
            </span>
            <span class="messages messages-3" >
              <%= @tale.content %>
            </span>
          </h1>
        </div>
        <div class="story_animation_second">
          <h1 class="story_anime_second" >
              <%= @subject.content %>
              <%= @purpose.content %>
              <%= @tale.content %>
          </h1>
        </div>
          <input type="hidden" name="subject_id" id="subject">
          <input type="hidden" name="purpose_id" id="purpose">
          <input type="hidden" name="tale_id" id="tale">
      </div>
    </div>
    <%# /お題作成 %>
    <%# 話作り %>
    <div class="story_text">
      <div class="text_img">
        <textarea name="text" cols="48" rows="600" maxlength="28800" class="text_form" id="text_form" size="130x26" >
        </textarea>
      </div>
      <div class="wrapper_no4">
        <button type="button" class="button_bird">
          <p class="button_bird__text">投稿する</p>
          <svg version="1.1" class="feather" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
              viewBox="0 0 75 38" style="enable-background:new 0 0 75 38;" xml:space="preserve">
          <g>
              <path d="M20.8,31.6c3.1-0.7,2.9-2.3,2,1c9.1,4.4,20.4,3.7,29.1-0.8l0,0c0.7-2.1,1-3.9,1-3.9c0.6,0.8,0.8,1.7,1,2.9
                  c4.1-2.3,7.6-5.3,10.2-8.3c0.4-2.2,0.4-4,0.4-4.1c0.6,0.4,0.9,1.2,1.2,2.1c4.5-6.1,5.4-11.2,3.7-13.5c1.1-2.6,1.6-5.4,1.2-7.7
                  c-0.5,2.4-1.2,4.7-2.1,7.1c-5.8,11.5-16.9,21.9-30.3,25.3c13-4,23.6-14.4,29.1-25.6C62.8,9,55.6,16.5,44.7,20.7
                  c2.1,0.7,3.5,1.1,3.5,1.6c-0.1,0.4-1.3,0.6-3.2,0.4c-7-0.9-7.1,1.2-16,1.5c1,1.3,2,2.5,3.1,3.6c-1.9-0.9-3.8-2.2-5.6-3.6
                  c-0.9,0.1-10.3,4.9-22.6-12.3C5.9,17.7,11.8,26.9,20.8,31.6z"/>
          </g>
          </svg>
          <span class="bird"></span>
          <span class="bird--1"></span>
          <span class="bird--2"></span>
          <span class="bird--3"></span>
          <span class="bird--4"></span>
          <span class="bird--5"></span>
          <span class="bird--6"></span>
          <span class="bird--7"></span>
          <span class="bird--8"></span>
          <span class="bird--9"></span>
          <span class="bird--10"></span>
          <span class="bird--11"></span>
          <span class="bird--12"></span>
          <span class="bird--13"></span>
          <span class="bird--14"></span>
          <span class="bird--15"></span>
          <span class="bird--16"></span>
          <span class="bird--17"></span>
          <span class="bird--18"></span>
          <span class="bird--19"></span>
          <span class="bird--20"></span>
          <span class="bird--21"></span>
          <span class="bird--22"></span>
          <span class="bird--23"></span>
          <span class="bird--24"></span>
          <span class="bird--25"></span>
          <span class="bird--26"></span>
          <span class="bird--27"></span>
          <span class="bird--28"></span>
          <span class="bird--29"></span>
          <span class="bird--30"></span>
        </button>
        <div class="return-top" >
          <a href="/" class="btn btn-top-page">トップページに戻る</a>
        </div>
      </div>
      <%# 話作りの終わり %>
  <% end %>
</div>

app/views/stories/rank.html.erb
<%= render "shared/header" %>

<div class="rank-main">
  <div class="rank-story">
    <ul class="rank-lists">
      <% @ranks.each.with_index(1) do |rank, i| %>
        <li class="rank-list">
          <div class="book-rank-name">
              <h2>第<span><%= i %></span>位</h2>
          </div>
          <%= link_to story_path(rank.id), method: :get do %>
            <div class="book-img-content">
              <%= image_tag @category[(rank.category_id)-1].image.url, class: "book-img" %>
            </div>
            <div class="rank-info">
              <h3 class="story-name">
                <span>
                  <%= @subject[(rank.subject_id)-1].content %><br>
                  <%= @purpose[(rank.purpose_id)-1].content %><br>
                  <%= @tale[(rank.tale_id)-1].content %>
                </span>
              </h3>
              <div class="rank-nickname">
                <p>
                  <%= rank.user.nickname %>
                </p>
              </div>
              <div class="rank-btn">
                <%= image_tag "star.png", class:"star-icon" %>
                <span class="star-count">
                  <%= rank.liked_users.count  %>
                </span>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <footer class="rank-footer">
    <%= image_tag "appstory-logo3.png" %>
  </footer>
</div>

app/views/stories/show.html.erb
<%= render "shared/header"%>

<div class="show-story">
  <div class="show-story-top">
  </div>
    <div class="show-story-main">
      <h3 class="name">
        <span>投稿者</span>:
        <a href="/users/<%= @story.user.id %>" class="show-name">
          <%= @story.user.nickname %>
        </a>
      </h3>
      <div class="show-star">
        <% if current_user.already_liked?(@story) %>
          <button class='show-star-btn'>
            <%= image_tag "star.png", class:"show-star-icon", size:"17x17" %>
            <%= button_to "", story_like_path(@story), method: :delete , id:"show-btn" %>
          </button>
        <% else %>
          <button class='show-star-btn'>
            <%= image_tag "star.png", class:"show-star-icon", size:"17x17" %>
          <%= button_to "", story_likes_path(@story) , id:"show-btn" %>
          </button>
        <% end %>
        <div class="show-like">
          <h3>お気に入り : </h3>
          <%= @story.likes.count %>
        </div>
      </div>
      <% if user_signed_in? && current_user.id == @story.user_id %>
        <ul class="more-list">
          <li>
            <%= link_to '編集', edit_story_path(@story.id), method: :get ,class:"btn btn-edit" %>
          </li>
          <li>
            <%= link_to '削除', story_path(@story.id), method: :delete, class:"btn btn-destroy" %>
          </li>
        </ul>
      <% end %>
    </div>
    <div class="show-story-box">
      <div class="story-text">
        <%= @story.text %>
      </div>
    </div>
  </div>
  <div class="comment-box">
    <div class="show-comment">
      <% if current_user %>
        <%= form_with(model: [@story, @comment],local: true) do |form| %>
        <%# <%= form. %>
          <%= form.text_area :text, class: "comment-text" %>
          <p class="comment-warn">
            相手のことを考え丁寧なコメントを心がけましょう。
            <br>
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
          </p>
          <div class= "comment-btn">
            <%# <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%> 
            <%= form.submit "コメントする", class: "comment-form"%>
          </div>
        <% end %>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p>
        </strong>
      <% end %>
    </div>
    <div class="comment-icon">
      <%# <i class="fas fa-comments"></i> %>
        コメント一覧
    </div>
    <div class="comments" id='comments'>
        <% @comments.reverse_each do |comment| %>
          <p>
            <strong class="comment-user"><%= comment.user.nickname %><span>：</span></strong>
            <%= comment.text %>
          </p>
        <% end %>
    </div>
  </div>
  <footer class="story_footer">
    <%= link_to image_tag("appstory.png", size:"280x80"), "/"   %>
  </footer>
</div>

app/views/tales/new.html.erb
<div class="create-page">
  <div class="user-logo">
    <%= link_to image_tag("appstory-radius.png", size:'150x150'), "/",  class:"user-show-image"%>
  </div>
  <div class="create-main">
    <h1>新規投稿ページ</h1>
    <p>(例：月に帰った話...)</p>
    <%= form_with(url: "/tales", method: :post, local: true) do |form| %>
      <input type="text" class="create-text"  name="content" size="50x10">
      <div class="create-submit">
        <button type="submit" class="create-button">
          投稿する
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-show-page">
  <div class="appstory-logo-user">
    <div class="user-logo">
      <%= link_to image_tag("appstory-radius.png", size:'150x150'), "/",  class:"user-show-image"%>
    </div>
    <div class="user-nickname-plate">
      <h2>
        <%= @nickname %><br><span>の作品</span>
      </h2>
    </div>
  </div>
  <div class="user-room">
    <ul class="user-room-lists" >
      <% @stories.each do |story| %>
        <li class="postit" >
          <%= link_to story_path(story.id), method: :get do %>
            <div class="tape"></div>
            <div class="user-story-info">
              <h3 class="user-story-tittle">
                <span>
                  <%= @subject[(story.subject_id)-1].content %><br>
                  <%= @purpose[(story.purpose_id)-1].content %><br>
                  <%= @tale[(story.tale_id)-1].content %>
                </span>
              </h3>
              <div class="user-star">
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'>
                  <%= story.liked_users.count  %>
                </span>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>